[package]
name = "lin-bus"
version = "0.1.0"
authors = ["Odhiambo Dormnic <d.odhiambo@carepay.co.ke>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
